def generate_html_report(problem_type, data, insights):
    """
    Generates a standalone HTML report combining data and LLM insights.
    """
    # Simple formatting for dicts if needed
    data_html = "<ul>"
    for k, v in data.items():
        if k != 'chart_data':
            if isinstance(v, list) and len(v) > 0 and isinstance(v[0], dict):
                data_html += f"<li><strong>{k}:</strong><ul>"
                for item in v:
                    data_html += "<li>" + ", ".join([f"{ik}: {iv}" for ik, iv in item.items()]) + "</li>"
                data_html += "</ul></li>"
            else:
                data_html += f"<li><strong>{k}:</strong> {v}</li>"
    data_html += "</ul>"
    
    insights_html = ""
    for k, v in insights.items():
        if isinstance(v, list):
            insights_html += f"<h3>{k.replace('_', ' ').title()}</h3><ul>"
            for item in v:
                insights_html += f"<li>{item}</li>"
            insights_html += "</ul>"
        else:
            insights_html += f"<h3>{k.replace('_', ' ').title()}</h3><p>{v}</p>"
            
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Consulting Report - {problem_type}</title>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 30px; }}
            h3 {{ color: #34495e; }}
            .card {{ background: #f8f9fa; border: 1px solid #e9ecef; border-radius: 5px; padding: 20px; margin-bottom: 20px; }}
            .footer {{ margin-top: 50px; font-size: 0.8em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <h1>Consulting Strategy Report: {problem_type}</h1>
        
        <div class="card">
            <h2>Executive Summary</h2>
            <p>{insights.get('executive_summary', 'No summary provided.')}</p>
        </div>
        
        <div class="card">
            <h2>Quantitative Analysis</h2>
            {data_html}
        </div>
        
        <div class="card">
            <h2>Strategic Insights</h2>
            {insights_html.replace('<h3>Executive Summary</h3><p>' + str(insights.get('executive_summary', '')) + '</p>', '')}
        </div>
        
        <div class="footer">
            Generated by Consulting Decision Engine
        </div>
    </body>
    </html>
    """
    
    return html_template
